language: bash

os:
  - linux

before_script:
  - sudo apt-get install shunit2 bash zsh
  - ./bootstrap.sh -f

script:
  - bash .redpill/tests/functions-tests.sh
  - zsh .redpill/tests/functions-tests.sh
